#!/usr/bin/env python3
"""Offline vector regeneration only: supply pinned v3.0.3 JS8_Mode/JS8.cpp and JS8.h.

Requires a C++17 compiler and Boost headers; neither is needed by normal tests.
JS8.h defaults to the input path with suffix .h; optionally pass it as argv[2].
Extracts upstream encode, Costas, alphabet, parity, CRC12 and BP definitions
verbatim, never links MiniShell.
"""
import hashlib
from pathlib import Path
import subprocess
import sys
import tempfile

source = Path(sys.argv[1]).read_bytes()
assert hashlib.sha256(source).hexdigest() == (
    'b72787f6e6473919872103997ef5dc9847810ff3e7783124a3961a2da2a86bf1')
s = source.decode()
header_path = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(sys.argv[1]).with_suffix('.h')
header = header_path.read_bytes()
assert hashlib.sha256(header).hexdigest() == (
    '8927db1d7e8151ff00333b9fe0524b0c907b56e9c0895221e37b6882d7790dd1')
h = header.decode()
costas = h[h.index('namespace Costas {'):h.index('} // namespace Costas')] + '}'
alphabet = s[s.index('constexpr std::string_view alphabet'):s.index('template <typename T> std::uint16_t CRC12')]
encode = s[s.index('void encode(int const type'):s.index('} // namespace JS8', s.index('void encode(int const type'))]
bp = s[s.index('constexpr int BP_MAX_ROWS'):s.index('} // namespace', s.index('int bpdecode174'))]
crc = s[s.index('template <typename T> std::uint16_t CRC12'):s.index('bool checkCRC12')]
parity = s[s.index('constexpr auto parity'):s.index('} // namespace', s.index('constexpr auto parity'))]
helper = r'''
#include <array>
#include <algorithm>
#include <numeric>
#include <cmath>
#include <cstdint>
#include <limits>
#include <string_view>
#include <iostream>
#include <stdexcept>
#include <type_traits>
#include <boost/crc.hpp>
constexpr int N=174, K=87, M=87;
'''+bp+alphabet+crc+parity+'namespace JS8 {\n'+costas+encode+'}\n'+r'''
int main() {
    std::cout << "/* Generated by js8_reference_oracle.py from pinned v3.0.3. */\n";
    std::cout << "static const struct golden vectors[] = {\n";
    for (int v=0; v<3; ++v) {
        std::array<uint8_t,11> bytes{};
        std::array<int8_t,87> info{};
        std::array<int8_t,174> cw{};
        uint32_t state=0x0528abcd;
        for (int i=0;i<75;++i) {
            state=state*1664525u+1013904223u;
            info[i]=v==0 ? 0 : v==1 ? i%2 : (state>>31);
            bytes[i/8] |= info[i] << (7-i%8);
        }
        auto crc=CRC12(bytes);
        bytes[9] |= (crc>>7)&0x1f;
        bytes[10]=(crc&0x7f)<<1;
        for (int i=0;i<87;++i) info[i]=(bytes[i/8]>>(7-i%8))&1;
        for (int i=0;i<87;++i) {
            std::size_t parityBits=0, parityByte=0;
            uint8_t parityMask=0x80;
            for (int j=0;j<87;++j) {
                parityBits += parity(i,j) && (bytes[parityByte]&parityMask);
                parityMask=(parityMask==1) ? (++parityByte,0x80) : (parityMask>>1);
            }
            cw[i]=parityBits&1;
            cw[i+87]=info[i];
        }
        // Adapt raw payload bits to the upstream encode interface only here.
        std::array<char,12> message{};
        for (int i=0;i<12;++i) {
            unsigned word=0;
            for (int j=0;j<6;++j) word=(word<<1)|info[i*6+j];
            message[i]=alphabet[word];
        }
        int type=(info[72]<<2)|(info[73]<<1)|info[74];
        std::array<int,79> tones{};
        JS8::encode(type, JS8::Costas::array(JS8::Costas::Type::ORIGINAL),
                    message.data(), tones.data());
        std::cout << "    {\n        \"";
        for(int i=0;i<75;++i) std::cout << int(info[i]);
        std::cout << "\",\n        " << crc << ",\n        \"";
        for(auto b:info) std::cout << int(b);
        std::cout << "\",\n        \"";
        for(auto b:cw) std::cout << int(b);
        std::cout << "\",\n        {";
        for (std::size_t i=0;i<tones.size();++i) {
            if (i) std::cout << ", ";
            std::cout << tones[i];
        }
        std::cout << "}\n    },\n";
        for (int damaged=0;damaged<2;++damaged) {
            std::array<float,174> llr{};
            for(int i=0;i<174;++i) llr[i]=cw[i] ? 4.0f : -4.0f;
            if(damaged) for(int i:{0,87,173}) llr[i]=cw[i] ? -0.25f : 0.25f;
            std::array<int8_t,87> recovered{};
            std::array<int8_t,174> decoded{};
            int errors=bpdecode174(llr,recovered,decoded);
            if(errors!=(damaged ? 3 : 0) || recovered!=info || decoded!=cw) return 1;
        }
    }
    std::cout << "};\n";
}
'''
with tempfile.TemporaryDirectory(prefix='js8-oracle-') as temp:
    cpp = Path(temp)/'oracle.cpp'
    exe = Path(temp)/'oracle'
    cpp.write_text(helper)
    subprocess.run(['c++', '-std=c++17', '-O0', str(cpp), '-o', str(exe)], check=True)
    subprocess.run([str(exe)], check=True)
