#!/usr/bin/env python3
"""Offline source-pinned Normal Huffman oracle; no MiniShell code or Qt.
Usage: js8_huffman_oracle.py Varicode.cpp Varicode.h > js8_huffman_vectors.h
"""
import hashlib
import json
from pathlib import Path
import re
import sys

assert len(sys.argv) == 3
for path, digest in zip(sys.argv[1:], (
    '2b4a877e7dae1a3fdd9141f4dd8af422185977d2e9363ad23ef6bc1918eaf53a',
    'dd7b8bf50466d0d2dc42b8c9ec05a72126363b3cd02c7492c5e2dcc9c9abb99d',
)):
    assert hashlib.sha256(Path(path).read_bytes()).hexdigest() == digest
source = Path(sys.argv[1]).read_text()
block = source.split('QMap<QString, QString> hufftable = {', 1)[1].split('};', 1)[0]
table = dict((json.loads(char), bits) for char, bits in re.findall(
    r'\{("(?:\\.|[^"\\])*")\s*,\s*"([01]+)"\}', block))
assert len(table) == 44


def pack(text):
    # packHuffMessage validates uppercase chars; huffEncode matches input as-is.
    assert all(char.upper() in table for char in text)
    frame = '10'
    consumed = 0
    for char in text:
        if char not in table:
            continue
        code = table[char]
        if len(frame) + len(code) >= 72:
            break
        frame += code
        consumed += 1
    return (frame + '0').ljust(72, '1'), consumed


def decode(app):
    assert app[:2] == '10'
    bits = app[1:]
    n = bits.rfind('0')
    assert n >= 1  # Restrict this oracle to an actual data-area sentinel.
    bits = bits[1:n]
    text = ''
    # Transcribe huffDecode's sorted QMap scan, including no break on a match.
    while bits:
        found = False
        for char in sorted(table):
            if bits.startswith(table[char]):
                text += char
                bits = bits[len(table[char]):]
                found = True
        if not found:
            break
    return text, n-1


print('/* Generated by js8_huffman_oracle.py from pinned v3.0.3. */')
print('static const struct huff_entry huff_entries[] = {')
for char, code in sorted(table.items()):
    print(f'    {{{json.dumps(char)}, "{code}"}},')
print('};\nstatic const struct huff_vector huff_vectors[] = {')
texts = ['HELLO', 'HELLO WORLD', 'CQ FIELD', 'ACK', '73', 'AG6AQ', 'K1ABC/P',
         'THE QUICK', ' '*40, 'E'*24, '"HELLO"', '']
for i, text in enumerate(texts):
    app, consumed = pack(text)
    decoded, count = decode(app)
    print(f'    {{{json.dumps(text)}, "{app}", {consumed}, {json.dumps(decoded)}, {count}, "{app}{i%8:03b}"}},')
# Decoder-only vector: HE plus incomplete final code 1111. Not encoder output.
app = ('10' + table['H'] + table['E'] + '1111' + '0').ljust(72, '1')
decoded, count = decode(app)
print(f'    {{NULL, "{app}", -1, {json.dumps(decoded)}, {count}, "{app}010"}},')
print('};')
