#!/usr/bin/env python3
"""Offline v3.0.3 formula oracle, independent of MiniShell production code.
Usage: js8_directed_oracle.py Varicode.cpp Varicode.h > js8_directed_vectors.h
"""
import hashlib
import json
from pathlib import Path
import re
import sys

assert len(sys.argv) == 3
for path, digest in zip(sys.argv[1:], (
    '2b4a877e7dae1a3fdd9141f4dd8af422185977d2e9363ad23ef6bc1918eaf53a',
    'dd7b8bf50466d0d2dc42b8c9ec05a72126363b3cd02c7492c5e2dcc9c9abb99d',
)):
    assert hashlib.sha256(Path(path).read_bytes()).hexdigest() == digest
source = re.sub(r'//[^\n]*', '', Path(sys.argv[1]).read_text())
base = dict((int(n) + 262177560, name) for name, n in re.findall(
    r'\{"([^"]+)",\s*nbasecall\s*\+\s*(\d+)\}', source))
assert len(base) == 54
cmd_block = source.split('QMap<QString, int> directed_cmds = {', 1)[1].split('};', 1)[0]
commands = {}
# QString ASCII key order: QMap::key returns the first matching key.
for name, code in sorted(re.findall(r'\{"([^"]*)",\s*(-?\d+)\}', cmd_block)):
    commands.setdefault(int(code), name)
assert set(range(32)) <= commands.keys()
alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ /@'


def pack_call(call):
    if call in base.values():
        return next(n for n, name in base.items() if name == call), 0
    portable = call.endswith('/P')
    call = call.removesuffix('/P')
    if call.startswith('3DA0'):
        call = '3D0' + call[4:]
    if call.startswith('3X') and 'A' <= call[2] <= 'Z':
        call = 'Q' + call[2:]
    permutations = [call]
    if 2 <= len(call) <= 5:
        permutations.append(' ' + call + ' ' * (5-len(call)))
    if 3 <= len(call) <= 5:
        permutations.append(call + ' ' * (6-len(call)))
    matched = None
    for word in permutations:
        match = re.search(r'([0-9A-Z ])([0-9A-Z])([0-9])([A-Z ])([A-Z ])([A-Z ])', word)
        if match:
            matched = match.group(0)
    assert matched is not None
    value = alphabet.index(matched[0])
    for i, radix in enumerate([36, 10, 27, 27, 27], 1):
        value = radix * value + alphabet.index(matched[i]) - (10 if i >= 3 else 0)
    return value, int(portable)


def unpack_call(value, portable):
    if value in base:
        return base[value]
    chars = []
    for _ in range(3):
        value, digit = divmod(value, 27)
        chars.append(alphabet[digit + 10])
    value, digit = divmod(value, 10)
    chars.append(alphabet[digit])
    value, digit = divmod(value, 36)
    chars.extend((alphabet[digit], alphabet[value]))
    call = ''.join(reversed(chars))
    if call.startswith('3D0'):
        call = '3DA0' + call[3:]
    if call.startswith('Q') and 'A' <= call[1] <= 'Z':
        call = '3X' + call[1:]
    return call.strip() + ('/P' if portable else '')


print('/* Generated by js8_directed_oracle.py from pinned v3.0.3. */')
print('static const char *const expected_commands[32] = {')
for code in range(32):
    print('    ' + json.dumps(commands[code]) + ',')
print('};\nstatic const struct call28_vector call28_vectors[] = {')
values = [0, 1, 262177559, 262177560, *sorted(base), 262177615, (1 << 28)-1]
values += [pack_call(c)[0] for c in ('AG6AQ', 'K1ABC', '3DA0XYZ', '3XY1ABC', 'QZ9ZZZ', 'K1A')]
# Generic internal spaces must be preserved, unlike callsign50.
values += [pack_call('AB1A C')[0]]
for value in values:
    print(f'    {{{value}, {json.dumps(unpack_call(value, 0))}, {json.dumps(unpack_call(value, 1))}}},')
print('};\nstatic const struct directed_vector directed_vectors[] = {')
frames = [('AG6AQ', 'K1ABC', 31, 0), ('AG6AQ', 'K1ABC', 14, 0),
          ('AG6AQ', 'K1ABC', 28, 0), ('AG6AQ/P', 'K1ABC', 31, 0),
          ('AG6AQ', 'K1ABC/P', 31, 0), ('AG6AQ/P', 'K1ABC/P', 14, 0),
          ('<....>', 'K1ABC', 14, 0), ('AG6AQ', 'K1ABC', 25, 19),
          ('AG6AQ', 'K1ABC', 29, 36), ('AG6AQ', 'K1ABC', 18, 63),
          ('AG6AQ', '@ALLCALL', 31, 0)]
for from_call, to_call, code, number6 in frames:
    f, fp = pack_call(from_call)
    t, tp = pack_call(to_call)
    payload = f'011{f:028b}{t:028b}{code:05b}{fp:b}{tp:b}{number6:06b}010'
    number = number6 - 31 if number6 else 0
    diagnostic = f' from={from_call} to={to_call} cmd="{commands[code]}"'
    if number6:
        diagnostic += f' num={number}'
    if code == 31:
        diagnostic += ' free_text=1'
    if code == 14:
        diagnostic += ' ack=1'
    if code == 28:
        diagnostic += ' end73=1'
    print(f'    {{"{payload}", "{from_call}", "{to_call}", {f}, {t}, {fp}, {tp}, {code}, {int(number6 != 0)}, {number}, {json.dumps(diagnostic)}}},')
print('};')
