#!/usr/bin/env python3
"""Offline v3.0.3 Varicode formula transcription; never imports production code.
Usage: python3 tests/js8_compound_oracle.py Varicode.cpp Varicode.h > tests/js8_compound_vectors.h
Sources are SHA-256 checked before generating the fixed fixtures. See js8_compound_vectors.md.
"""
import hashlib
import json
from pathlib import Path
import re
import sys

for name, digest in zip(sys.argv[1:], (
    '2b4a877e7dae1a3fdd9141f4dd8af422185977d2e9363ad23ef6bc1918eaf53a',
    'dd7b8bf50466d0d2dc42b8c9ec05a72126363b3cd02c7492c5e2dcc9c9abb99d',
)):
    assert hashlib.sha256(Path(name).read_bytes()).hexdigest() == digest
assert len(sys.argv) == 3
alphabet = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ /@'
radices = [39, 38, 38, 2, 38, 38, 38, 2, 38, 38, 38]


def pack_call(value):
    word = re.sub('[^A-Z0-9 /@]', '', value)
    for position in (3, 7):
        if len(word) > position and word[position] != '/':
            word = word[:position] + ' ' + word[position:]
    word = word.ljust(11)
    digits = [int(c == '/') if i in (3, 7) else alphabet.index(c)
              for i, c in enumerate(word[:11])]
    # Weighted sum, as in packAlphaNumeric50.
    value = 0
    for i, digit in enumerate(digits):
        weight = 1
        for radix in radices[i+1:]:
            weight *= radix
        value += digit * weight
    return value


def unpack_call(value):
    chars = []
    for position in range(10, -1, -1):
        value, digit = divmod(value, radices[position])
        chars.append((' /'[digit] if position in (3, 7) else alphabet[digit]))
    return ''.join(reversed(chars)).replace(' ', '')


def pack_grid(grid):
    if not grid:
        return 32767
    # grid2deg's appended 'mm', C++ int truncation, then packGrid.
    longitude = 180 - 20*(ord(grid[0])-65) - 2*int(grid[2]) - 5*12.5/60
    latitude = -90 + 10*(ord(grid[1])-65) + int(grid[3]) + 2.5*12.5/60
    return ((int(longitude)+180)//2)*180 + int(latitude+90)


def unpack_grid(value):
    if value > 32400:
        return ''
    latitude = value % 180 - 90
    longitude = value // 180 * 2 - 180 + 2
    if longitude < -180:
        longitude += 360
    if longitude > 180:
        longitude -= 360
    nlong = int(60.0*(180.0-longitude)/5)
    nlat = int(60.0*(latitude+90)/2.5)
    return (chr(65+nlong//240) + chr(65+nlat//240)
            + str((nlong % 240)//24) + str((nlat % 240)//24))


print('/* Generated by js8_compound_oracle.py; pinned v3.0.3 formulas. */')
print('static const struct compound_vector compound_vectors[] = {')
frames = [(0, 'AG6AQ', pack_grid('CM97'), 0),
          (0, 'AG6AQ', 32768 | pack_grid('CM97'), 4),
          (0, 'KN4CRD', 65535, 7),
          (1, 'KN4CRD/P', pack_grid('EM73'), 0),
          (1, 'VE3/LB9YHX', 32767, 5),
          (2, 'KN4CRD/P', 32442, 6)]
for cls, call, extra, subtype in frames:
    packed = pack_call(call)
    payload = f'{cls:03b}{packed:050b}{extra:016b}{subtype:03b}010'
    grid = unpack_grid(extra & 32767 if cls == 0 else extra)
    print(f'    {{"{payload}", {cls}, "{unpack_call(packed)}", {extra}, {subtype}, "{grid}"}},')
print('};\nstatic const struct call_vector call_vectors[] = {')
values = [0, 1, 37, 38, (1 << 49), (1 << 50)-1]
values += [pack_call(s) for s in ('KN4CRD/QRP', 'VE3/LB9YHX', 'ABC/DEF/GHI', '@RACES', 'A B C', '           ', '///////////')]
for value in values:
    print(f'    {{UINT64_C({value}), {json.dumps(unpack_call(value))}}},')
print('};\nstatic const struct grid_vector grid_vectors[] = {')
for value in [0, 1, 179, 180, pack_grid('CM97'), pack_grid('EM73'), 32399, 32400, 32401, 32410, 32766, 32767, 65535]:
    print(f'    {{{value}, "{unpack_grid(value)}"}},')
print('};')
