#!/usr/bin/env python3
"""Offline independent v3.0.3 JSC dense decoder/map oracle. No MiniShell imports.
Usage: js8_jsc_oracle.py JSC.cpp JSC.h JSC_map.cpp > js8_jsc_vectors.h
"""
import ast
import hashlib
from pathlib import Path
import re
import sys

assert len(sys.argv) == 4
for path, digest in zip(sys.argv[1:], (
    '0f1c974a96fd65e043b1a4dbdb69a9ae43e42dafe81f5f22f196b09596dbcdeb',
    '3edfda65865dc4ede66730113c1c7250861253d78ed83f17626ce55c79b0f1d8',
    'ab2bd62ef594f4629a2c93b6de43f5469b1fd6fe67ebf4d24f915bd11ccef813',
)):
    assert hashlib.sha256(Path(path).read_bytes()).hexdigest() == digest
entries = {}
for raw, size, index in re.findall(r'\{\s*("(?:\\.|[^"\\])*")\s*(?:/\*.*?\*/\s*)*,\s*(\d+)\s*,\s*(\d+)\s*\}', Path(sys.argv[3]).read_text()):
    entries[int(index)] = ast.literal_eval(raw).encode('latin-1')
assert len(entries) == 262144
base = [0]
for k in range(7):
    base.append(base[-1] + 7 * 9**k)
used = set()


def decode(bits):
    # Deliberately retain upstream's two-pass nibble/separator representation.
    nibbles, separators = [], set()
    pos = 0
    while pos + 4 <= len(bits):
        nibble = int(bits[pos:pos+4], 2)
        nibbles.append(nibble)
        pos += 4
        if nibble < 7:
            if pos < len(bits) and bits[pos] == '1':
                separators.add(len(nibbles)-1)
            pos += 1
    start, words, out = 0, 0, b''
    while start < len(nibbles):
        k, j = 0, 0
        while start+k < len(nibbles) and nibbles[start+k] >= 7:
            j = j*9 + nibbles[start+k]-7
            k += 1
        if j >= 262144 or start+k >= len(nibbles):
            break
        # k>7 is outside upstream's base array; reject its meaningless range.
        if k >= len(base):
            break
        j = j*7 + nibbles[start+k] + base[k]
        if j >= 262144:
            break
        used.add(j)
        out += entries[j] + (b' ' if start+k in separators else b'')
        words += 1
        start += k+1
    return out, words


def word(index, sep=0):
    # Exact JSC::codeword arithmetic, only for offline RX fixtures.
    bits = f'{index%7:04b}{sep}'
    x = index//7
    while x:
        x -= 1
        bits = f'{x%9+7:04b}' + bits
        x //= 9
    return bits


def literal(data):
    return '"' + ''.join(chr(b) if 32 <= b < 127 and b not in (34, 92)
                         else '\\%03o' % b for b in data) + '"'


real = '111001011101001010000111001011100000101011000001100010000111111111111111010'
contents = [word(i) for i in (0, 6, 7, 69, 70, 81, 637, 10000, 262143)]
contents += [word(0, 1)+word(7, 1)+word(6), word(81)[:-1], word(7)+'101',
             word(0)+'11111111', word(0)+word(262144), '0111'*8+'0000',
             ('00001'*13)+'0000', '']
# Include quotes, backslashes and Latin-1 independently selected from the map.
for predicate in (lambda x: b'"' in x, lambda x: b'\\' in x, lambda x: any(b >= 128 for b in x)):
    index = next(i for i in range(262144) if predicate(entries[i]))
    contents.append(word(index))
rows = []
for n, content in enumerate(contents):
    assert len(content) <= 69
    payload = ('11'+content+'0').ljust(72, '1') + f'{n%8:03b}'
    text, words = decode(content)
    rows.append((payload, text, len(content), words))
sentinel = real[:72].rfind('0')
text, words = decode(real[2:sentinel])
rows.append((real, text, sentinel-2, words))
print('A_2_1 independent Latin-1 text:', repr(text), file=sys.stderr)
print('A_2_1 text hex:', text.hex(), file=sys.stderr)
print('/* Generated by js8_jsc_oracle.py from pinned v3.0.3 sources. */')
print('static const struct jsc_word jsc_words[] = {')
for index in sorted(used):
    print(f'    {{{index}, {literal(entries[index])}}},')
print('};\nstatic const struct jsc_vector jsc_vectors[] = {')
for payload, text, count, words in rows:
    print(f'    {{"{payload}", {literal(text)}, {count}, {words}}},')
print('};')
