#pragma once
static const char webfs_page[] =
"<!doctype html>\n"
"<html lang=\"en\"><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>MiniShell WebFS</title>\n"
"<style>body{font:16px system-ui,sans-serif;max-width:55em;margin:auto;padding:1em;color:#17202a;background:#f8f9fa}button,a{font:inherit;padding:.6em;display:inline-block}button{cursor:pointer}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:.4em;border-bottom:1px solid #ccc;overflow-wrap:anywhere}#error{color:#a00;white-space:pre-wrap}#path{overflow-wrap:anywhere}nav{display:flex;flex-wrap:wrap;gap:.4em}</style>\n"
"<h1>MiniShell WebFS</h1><p>Read-only files. Press Q or Esc on MiniShell to stop.</p>\n"
"<nav><button id=\"flash\">/flash</button><button id=\"sd\">/sd</button><button id=\"parent\">Parent</button><button id=\"refresh\">Refresh</button></nav>\n"
"<h2 id=\"path\">/flash</h2><p id=\"space\"></p><p id=\"error\" role=\"alert\"></p>\n"
"<table><thead><tr><th>Name</th><th>Bytes</th></tr></thead><tbody id=\"entries\"></tbody></table>\n"
"<script>\n"
"'use strict';\n"
"const el=id=>document.getElementById(id);let path='/flash',sequence=0;\n"
"function parent(p){const root=p.startsWith('/flash')?'/flash':'/sd';return p===root?root:p.slice(0,p.lastIndexOf('/'));}\n"
"async function browse(p){const request=++sequence;path=p;el('path').textContent=p;el('parent').disabled=parent(p)===p;el('error').textContent='';el('space').textContent='Loading\u2026';el('entries').replaceChildren();\n"
"try{const response=await fetch('/api/list?path='+encodeURIComponent(p),{cache:'no-store'});const data=await response.json();if(request!==sequence)return;if(!response.ok)throw Error(data.error||'Request failed');\n"
"el('space').textContent=`Total ${data.total} \u00b7 Used ${data.used} \u00b7 Free ${data.free} bytes`;\n"
"data.entries.sort((a,b)=>(a.type===b.type?0:a.type==='dir'?-1:1)||a.name.localeCompare(b.name));\n"
"for(const entry of data.entries){const row=document.createElement('tr'),name=document.createElement('td'),size=document.createElement('td'),link=document.createElement('a');const child=p+'/'+entry.name;link.textContent=entry.name+(entry.type==='dir'?'/':'');\n"
"if(entry.type==='dir'){link.href='#';link.onclick=event=>{event.preventDefault();browse(child);};}else{link.href='/api/file?path='+encodeURIComponent(child);link.download=entry.name;}\n"
"name.append(link);size.textContent=entry.type==='file'?String(entry.size):'Directory';row.append(name,size);el('entries').append(row);}\n"
"if(!data.entries.length)el('space').textContent+=' \u00b7 Empty directory';\n"
"}catch(error){if(request!==sequence)return;el('space').textContent='';el('error').textContent='Cannot list '+p+': '+error.message+'. Check the volume and Wi-Fi connection; interrupted responses are not complete listings.';}}\n"
"el('flash').onclick=()=>browse('/flash');el('sd').onclick=()=>browse('/sd');el('parent').onclick=()=>browse(parent(path));el('refresh').onclick=()=>browse(path);browse(path);\n"
"</script></html>\n"
;
