#pragma once
static const char adv_ft8_web_page[] =
"<!doctype html>\n"
"<html lang=\"en\"><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>MiniShell ADV front panel</title>\n"
"<style>body{font:16px system-ui;background:#171717;color:white;max-width:38em;margin:auto;padding:1em}#screen{display:grid;grid-template-columns:repeat(20,1ch);width:20ch;font:clamp(16px,4.2vw,28px) monospace;white-space:pre;background:black;border:1px solid #888}#screen span{height:1.4em;color:white;background:black}.inverse{color:black!important;background:white!important}button,input{font:inherit;padding:.6em;margin:.2em}#status{min-height:1.5em}</style>\n"
"<h1>ADV front panel</h1><div id=\"screen\" aria-label=\"ADV 20 by 7 display\"></div>\n"
"<p id=\"status\" role=\"status\">Connecting\u2026</p>\n"
"<label>Type keys <input id=\"keys\" type=\"text\" autocapitalize=\"off\" autocomplete=\"off\" autocorrect=\"off\" spellcheck=\"false\"></label>\n"
"<div id=\"buttons\"></div><p>Local and browser keys share the same front panel. Q and Esc follow the application\u2019s normal behavior.</p>\n"
"<script>\n"
"'use strict';\n"
"const screen=document.getElementById('screen'),status=document.getElementById('status'),input=document.getElementById('keys');\n"
"const cells=Array.from({length:140},()=>{const cell=document.createElement('span');cell.textContent=' ';screen.append(cell);return cell;});\n"
"const special={Escape:8,Enter:5,Backspace:6,ArrowUp:1,ArrowDown:2,ArrowLeft:3,ArrowRight:4,PageUp:12,PageDown:13,Tab:9};\n"
"let polling=false,sending=false;const pending=[];\n"
"async function poll(){if(polling)return;polling=true;try{const response=await fetch('/api/screen',{cache:'no-store'});if(!response.ok)throw Error('Screen unavailable');const bytes=new Uint8Array(await response.arrayBuffer());if(bytes.length!==284)throw Error('Incomplete screen');for(let i=0;i<140;i++){cells[i].textContent=String.fromCharCode(bytes[4+i]);cells[i].classList.toggle('inverse',Boolean(bytes[144+i]&1));}if(status.textContent==='Connecting\u2026'||status.textContent.startsWith('Screen:'))status.textContent='Connected';}catch(error){status.textContent='Screen: '+error.message;}finally{polling=false;}}\n"
"async function drain(){if(sending)return;sending=true;try{while(pending.length){const query=pending.shift();try{const response=await fetch('/api/key?'+query,{method:'PUT'});if(!response.ok)throw Error(await response.text());status.textContent='Key sent';}catch(error){pending.length=0;status.textContent='Key: '+error.message+'; not retried';break;}}}finally{sending=false;}}\n"
"function key(kind,value,mods=0){if(pending.length>=16){status.textContent='Key queue full; key not sent';return;}pending.push(kind+'='+value+'&m='+mods);drain();}\n"
"function modifiers(event){return (event.shiftKey?1:0)|(event.ctrlKey?2:0)|(event.altKey?4:0)|(event.metaKey?16:0);}\n"
"document.addEventListener('keydown',event=>{if(event.isComposing)return;if(Object.hasOwn(special,event.key)){event.preventDefault();key('k',special[event.key],modifiers(event));}else if(event.key.length===1&&event.key.charCodeAt(0)>=32&&event.key.charCodeAt(0)<=126){event.preventDefault();key('c',event.key.charCodeAt(0),modifiers(event));}});\n"
"input.addEventListener('input',event=>{if(event.isComposing)return;const value=input.value;input.value='';for(const ch of value.slice(0,16)){const code=ch.codePointAt(0);if(code>=32&&code<=126)key('c',code);}});\n"
"input.addEventListener('beforeinput',event=>{if(event.inputType==='deleteContentBackward'){event.preventDefault();key('k',6);}else if(event.inputType==='insertLineBreak'||event.inputType==='insertParagraph'){event.preventDefault();key('k',5);}});\n"
"for(const [label,value] of [['Esc',8],['Enter',5],['Backspace',6],['\u2191',1],['\u2193',2],['\u2190',3],['\u2192',4],['Page Up',12],['Page Down',13],['Tab',9]]){const button=document.createElement('button');button.textContent=label;button.onclick=()=>key('k',value);document.getElementById('buttons').append(button);}\n"
"setInterval(poll,250);poll();\n"
"</script></html>\n"
;
