#pragma once
static const char webfs_page[] =
"<!doctype html>\n"
"<html lang=\"en\"><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
"<title>MiniShell WebFS</title>\n"
"<style>body{font:16px system-ui,sans-serif;max-width:55em;margin:auto;padding:1em;color:#17202a;background:#f8f9fa}button,a{font:inherit;padding:.6em;display:inline-block}button{cursor:pointer}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:.4em;border-bottom:1px solid #ccc;overflow-wrap:anywhere}#error{color:#a00;white-space:pre-wrap}#path{overflow-wrap:anywhere}nav{display:flex;flex-wrap:wrap;gap:.4em}</style>\n"
"<h1>MiniShell WebFS</h1><p>Press Q or Esc on MiniShell to stop. Directory deletion requires an empty directory.</p>\n"
"<nav><button id=\"flash\">/flash</button><button id=\"sd\">/sd</button><button id=\"parent\">Parent</button><button id=\"refresh\">Refresh</button></nav>\n"
"<h2 id=\"path\">/flash</h2><p id=\"space\"></p><p id=\"status\" role=\"status\"></p><p id=\"error\" role=\"alert\"></p>\n"
"<p><input id=\"files\" type=\"file\" multiple><button id=\"upload\">Upload</button><button id=\"mkdir\">New Directory</button></p>\n"
"<table><thead><tr><th>Name</th><th>Bytes</th><th>Actions</th></tr></thead><tbody id=\"entries\"></tbody></table>\n"
"<script>\n"
"'use strict';\n"
"const el=id=>document.getElementById(id);let path='/flash',entries=[],busy=false,ready=false;\n"
"function parent(p){const root=p.startsWith('/flash')?'/flash':'/sd';return p===root?root:p.slice(0,p.lastIndexOf('/'));}\n"
"function controls(){document.querySelectorAll('button,input').forEach(x=>x.disabled=busy);el('parent').disabled=busy||parent(path)===path;el('upload').disabled=busy||!ready;el('mkdir').disabled=busy||!ready;}\n"
"function child(name){if(!name||name==='.'||name==='..'||/[\\/\\\\\\x00-\\x1f\\x7f]/.test(name))throw Error('Enter one file or directory name');return path+'/'+name;}\n"
"function existing(name){return entries.find(x=>x.name.toUpperCase()===name.toUpperCase());}\n"
"async function request(url,method,body){const response=await fetch(url,{method,body,cache:'no-store'});const data=await response.json();if(!response.ok)throw Error(data.error||'Request failed');return data;}\n"
"function action(cell,label,run){const button=document.createElement('button');button.textContent=label;button.onclick=()=>operate(run);cell.append(button);}\n"
"async function listing(p){ready=false;entries=[];path=p;el('path').textContent=p;el('space').textContent='Loading\u2026';el('entries').replaceChildren();\n"
"try{const data=await request('/api/list?path='+encodeURIComponent(p),'GET');entries=data.entries;el('space').textContent=`Total ${data.total} \u00b7 Used ${data.used} \u00b7 Free ${data.free} bytes`;\n"
"entries.sort((a,b)=>(a.type===b.type?0:a.type==='dir'?-1:1)||a.name.localeCompare(b.name));\n"
"for(const entry of entries){const row=document.createElement('tr'),name=document.createElement('td'),size=document.createElement('td'),actions=document.createElement('td'),link=document.createElement('a');const full=p+'/'+entry.name;link.textContent=entry.name+(entry.type==='dir'?'/':'');\n"
"if(entry.type==='dir'){link.href='#';link.onclick=event=>{event.preventDefault();browse(full);};}else{link.href='/api/file?path='+encodeURIComponent(full);link.download=entry.name;action(actions,'Rename',async()=>{const next=prompt('New filename',entry.name);if(next===null)return;const to=child(next),found=existing(next);if(found&&found!==entry){if(found.type==='dir')throw Error('Destination is a directory');if(!confirm('Replace '+next+'?'))return;}await request('/api/rename?from='+encodeURIComponent(full)+'&to='+encodeURIComponent(to),'PUT');await listing(p);el('status').textContent='Renamed '+entry.name;});}\n"
"action(actions,'Delete',async()=>{if(!confirm('Delete '+entry.name+(entry.type==='dir'?' (empty directory only)':'')+'?'))return;await request('/api/'+(entry.type==='dir'?'dir':'file')+'?path='+encodeURIComponent(full),'DELETE');await listing(p);el('status').textContent='Deleted '+entry.name;});\n"
"name.append(link);size.textContent=entry.type==='file'?String(entry.size):'Directory';row.append(name,size,actions);el('entries').append(row);}\n"
"if(!entries.length)el('space').textContent+=' \u00b7 Empty directory';ready=true;\n"
"}catch(error){el('space').textContent='';throw Error('Cannot list '+p+': '+error.message);}}\n"
"async function operate(run){if(busy)return;busy=true;controls();el('error').textContent='';el('status').textContent='';try{await run();}catch(error){el('error').textContent=error.message+'. Check storage and Wi-Fi; refresh before retrying an interrupted operation.';}finally{busy=false;controls();}}\n"
"function browse(p){return operate(()=>listing(p));}\n"
"el('upload').onclick=()=>operate(async()=>{const files=Array.from(el('files').files);if(!files.length)throw Error('Choose files to upload');for(const file of files){const target=child(file.name),found=existing(file.name);if(found){if(found.type==='dir')throw Error('Destination is a directory: '+file.name);if(!confirm('Replace '+file.name+'?'))continue;}el('status').textContent='Uploading '+file.name+'\u2026';await request('/api/file?path='+encodeURIComponent(target),'PUT',file);await listing(path);el('status').textContent='Uploaded '+file.name;}el('files').value='';});\n"
"el('mkdir').onclick=()=>operate(async()=>{const name=prompt('Directory name');if(name===null)return;await request('/api/dir?path='+encodeURIComponent(child(name)),'PUT');await listing(path);el('status').textContent='Created '+name;});\n"
"el('flash').onclick=()=>browse('/flash');el('sd').onclick=()=>browse('/sd');el('parent').onclick=()=>browse(parent(path));el('refresh').onclick=()=>browse(path);browse(path);\n"
"</script></html>\n"
;
